apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mariusjacobs/helm-guestbook.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: helm-guestbook

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true